mode: "prod"
port: "9091"
local:
  redis:
    dsn: "localhost:6379"
  kafka:
    dsn: "localhost:9092"
prod:
  mysql:
    dsn: "root:example@tcp(localhost:3306)/keypass?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    dsn: "localhost:6379"
  kafka:
    dsn: "localhost:9092"